### ISSUE TITLE
npm run build errors on arm64

### ISSUE THREAD

**Issue by step21** [zotero/zotero-standalone-build#83]
AFAIK, it is possible to run on arm64 f.e. by repackaging firefox packages and x86_64 zotero package, as the arch package did. Preferably, I would build by source. So far, I always get node/npm errors on `npm run build`.
The error seems to be in pdf-worker/pdf.js - on the docs it still says node version 8 or higher. Is that still correct?

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/florian/.nvm/versions/node/v8.17.0/bin/node',
1 verbose cli   '/home/florian/.nvm/versions/node/v8.17.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.13.4
3 info using node@v8.17.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle zotero@5.0.0~prebuild: zotero@5.0.0
6 info lifecycle zotero@5.0.0~build: zotero@5.0.0
7 verbose lifecycle zotero@5.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle zotero@5.0.0~build: PATH: /home/florian/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/florian/zotero-client/node_modules/.bin:/home/florian/.nvm/versions/node/v8.17.0/bin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle zotero@5.0.0~build: CWD: /home/florian/zotero-client
10 silly lifecycle zotero@5.0.0~build: Args: [ '-c', 'node ./scripts/build.js' ]
11 silly lifecycle zotero@5.0.0~build: Returned: code: 1  signal: null
12 info lifecycle zotero@5.0.0~build: Failed to exec build script
13 verbose stack Error: zotero@5.0.0 build: `node ./scripts/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/florian/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/florian/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid zotero@5.0.0
15 verbose cwd /home/florian/zotero-client
16 verbose Linux 5.12.4-1-MANJARO-ARM
17 verbose argv "/home/florian/.nvm/versions/node/v8.17.0/bin/node" "/home/florian/.nvm/versions/node/v8.17.0/bin/npm" "run" "build"
18 verbose node v8.17.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error zotero@5.0.0 build: `node ./scripts/build.js`
22 error Exit status 1
23 error Failed at the zotero@5.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by step21** [comment]
fixed for now with linking `pdf-worker/build/worker.js to pdf-worker/build/pdf-worker.js`
